apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-api-operator
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.13.0
    helm:
      releaseName: capi-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: capi-operator-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
