apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.ops.com/test/cluster_api.git
    targetRevision: HEAD
    path: management-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-app
