apiVersion: v1
kind: Namespace
metadata:
  name: capa-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: capo-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: caaph-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.8.5
  manager:
    featureGates:
      ClusterResourceSet: true

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-bootstrap-system
spec:
  version: v1.8.5
  manager:
    featureGates:
      KubeadmBootstrapFormatIgnition: true

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.8.5
  manager:
    featureGates:
      KubeadmBootstrapFormatIgnition: true

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: AddonProvider
metadata:
  name: helm
  namespace: caaph-system
spec:
  version: v0.2.6

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-variables
  namespace: capa-system
type: Opaque
data:
  AWS_B64ENCODED_CREDENTIALS: xxx

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: aws
  namespace: capa-system
spec:
  version: v2.1.4
  configSecret:
    name: aws-variables
  deployment:
    containers:
      - name: manager
        args:
          # These are controller flags that are specific to a provider; usage
          # is reserved for advanced scenarios only.
          "--awscluster-concurrency": "12"
          "--awsmachine-concurrency": "11"

---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-cloud-config
  namespace: capo-system
data:
  cacert: Cg==
  clouds.yaml: xxx

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capo-system
spec:
  version: v0.11.2
