apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-gitlab
  namespace: backstage-sample
  labels:
    app: nginx
    backstage.io/kubernetes-id: backstage-example-frontend
spec:
  selector:
    matchLabels:
      app: nginx
      backstage.io/kubernetes-id: backstage-example-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        backstage.io/kubernetes-id: backstage-example-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
