http:
  routers:
    authelia:
      rule: "Host(`authelia.example.com`)"
      service: authelia
      tls: {}
    frontend:
      rule: "Host(`frontend.example.com`)"
      service: frontend
      middlewares:
        - "authelia"
      tls: {}
    backend:
      rule: "Host(`backend.example.com`)"
      service: backend
      middlewares:
        - "authelia"
      tls: {}
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
  services:
    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091
    frontend:
      loadBalancer:
        servers:
          - url: http://frontend:3000
    backend:
      loadBalancer:
        servers:
          - url: http://backend:8000
