---
apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-example
  labels:
    app: flask-k8s-example
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask-k8s-example
