services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json" # Do we need this for v2 ? Seems to be running without this.
      - "./config.yml:/etc/jaeger/config.yml"
    command: ["--config", "/etc/jaeger/config.yml"]
    ports:
      - "16686:16686"
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.119.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - loki
      - prometheus
  loki:
    container_name: loki
    image: grafana/loki
    ports:
      - "3100:3100"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command: ["--config.file=/etc/promtheus/protmetheus.yml"]
    volumes:
      - ./prometheus.yml:/etc/promtheus/protmetheus.yml
    ports:
      - "9090:9090"
