FROM python:3.14-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY *.py .
RUN chmod +x sync.py && ln -s /app/sync.py /usr/local/bin/sync

ENTRYPOINT ["sync"]
CMD ["run"]
