apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:test-role, applications, create, default/*, allow
    p, role:test-role, applications, get, default/*, allow
    p, role:test-role, applications, update, default/*, allow
    p, role:test-role, applications, delete, default/*, allow
    p, role:test-role, applications, sync, default/*, allow
    p, role:test-role, applications, override, default/*, allow
    g, backstage, role:test-role
  policy.default: role:readonly
