apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.centre.com/gitlab/flask-k8s-manifest.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://10.0.0.12:6443
    namespace: default
