services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    restart: always
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 5044:5044
