apiVersion: v1
kind: Secret
metadata:
  name: argocd-basic-auth
  namespace: flask-app
type: kubernetes.io/basic-auth
data:
  username: xxxx
  password: xxxx

---
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-basic-auth
  namespace: flask-app
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://<hostname>"]
      helper = store
  .git-credentials: |
    https://gitlab:password@gitlab.centre.com

---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-basic-auth
  namespace: flask-app
data:
  config.json: |
    xxxx
