---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: flask-app

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-webhook
  namespace: flask-app
rules:
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clustertriggerbindings"
      - "clusterinterceptors"
      - "eventlisteners"
      - "triggerbindings"
      - "triggertemplates"
      - "triggers"
      - "interceptors"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "tekton.dev"
    resources:
      - "pipelineruns"
      - "taskruns"
    verbs:
      - "create"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-webhook
  namespace: flask-app
subjects:
  - kind: ServiceAccount
    name: webhook
    namespace: flask-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-webhook
