---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: my-cluster-openstack
  namespace: capo-system
spec:
  externalNetwork:
    id: bac31e0e-0804-46cf-a944-5daff4073501
  identityRef:
    cloudName: kolla-admin
    name: openstack-cloud-config
  managedSubnets:
    - cidr: 10.6.0.0/24
      dnsNameservers:
        - 8.8.8.8

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster2
  namespace: capo-system
  labels:
    cloud: openstack
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: openstack-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: my-cluster-openstack

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: openstack-control-plane
  namespace: capo-system
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
      networking:
        podSubnet: "10.244.0.0/16"
    files: []
    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          systemd:
            units:
            - name: coreos-metadata-sshkeys@.service
              enabled: true
            - name: kubeadm.service
              enabled: true
              dropins:
              - name: 10-flatcar.conf
                contents: |
                  [Unit]
                  Requires=containerd.service coreos-metadata.service
                  After=containerd.service coreos-metadata.service

                  [Service]
                  EnvironmentFile=/run/metadata/flatcar
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///${COREOS_OPENSTACK_INSTANCE_UUID}
        name: ${COREOS_OPENSTACK_HOSTNAME}
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///${COREOS_OPENSTACK_INSTANCE_UUID}
        name: ${COREOS_OPENSTACK_HOSTNAME}
    preKubeadmCommands:
      - export COREOS_OPENSTACK_HOSTNAME=${COREOS_OPENSTACK_HOSTNAME%.*}
      - export COREOS_OPENSTACK_INSTANCE_UUID=${COREOS_OPENSTACK_INSTANCE_UUID}
      - envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp
      - mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: openstack-control-plane
  replicas: 1
  version: v1.30.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: openstack-control-plane
  namespace: capo-system
spec:
  template:
    spec:
      flavor: m1.medium
      image:
        filter:
          name: flatcar-3975.2.2-k8s-1.30.5-amd64
      sshKeyName: kolla_ssh
