apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: flannel
  namespace: capo-system
spec:
  clusterSelector:
    matchLabels: {}
  releaseName: flannel
  repoURL: https://flannel-io.github.io/flannel/
  chartName: flannel
  namespace: kube-flannel
  valuesTemplate: |
    podCidr: "10.244.0.0/16"
