apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: openstack-cloud-controller-manager
  namespace: capo-system
spec:
  clusterSelector:
    matchLabels:
      cloud: openstack
  releaseName: openstack-ccm
  repoURL: https://kubernetes.github.io/cloud-provider-openstack
  chartName: openstack-cloud-controller-manager
  namespace: kube-system
  valuesTemplate: |
    cloudConfig:
      global:
        auth-url: http://xxx
        username: admin
        password: xxx
        user-domain-name: Default
        region: RegionOne
        tenant-name: admin
        tenant-domain-name: Default
      networking:
      loadBalancer:
        subnet-id: 02743792-d2e0-4d8a-a021-3391f8f8cba4
        floating-network-id: bac31e0e-0804-46cf-a944-5daff4073501
      blockStorage:
      metadata:
      route:
