services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - 5601:5601
    depends_on:
      - es01
volumes:
  esdata_01:
    name: esdata_01
    driver: local
